general:    #Make for compile and run.
	javac -d classfiles *.java
	java -cp classfiles Main

doc:		#Make for creating Javadoc.
	javadoc -d doc **/*.java

rm:		#Make for cleaning class files.
	rm -r ./classfiles

rmdoc:	#Make for cleaning javadoc files.
	rm -r ./doc

#Suleyman Golbol 1801042656